In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/dataset.csv")

In [3]:
df.shape

(114000, 21)

In [4]:
group1 = df.copy().groupby(["track_name", "artists"], as_index=False).agg(list)

In [5]:
group1.shape

(81343, 21)

In [6]:
group1.head(5)

,track_name,artists,Unnamed: 0,track_id,album_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,!I'll Be Back!,Rilès,[36750],[0fROT4kK5oTm8xO8PX6EJF],[!I'll Be Back!],[52],[178533],[True],[0.823],[0.612],...,[-7.767],[1],[0.248],[0.168],[0.0],[0.109],[0.688],[142.959],[4],[french]
1,"""A"" You're Adorable",Brian Hyland,[92751],[1hH0t381PIXmUVWyG1Vj3p],[The Bashful Blond],[39],[151680],[False],[0.615],[0.375],...,[-10.362],[0],[0.0319],[0.482],[0.0],[0.111],[0.922],[110.72],[4],[rockabilly]
2,"""C"" IS FOR COOKIE",Little Apple Band,[66970],[1B45DvGMoFWdbAEUH2qliG],[The Favorite Songs Of Sesame Street],[32],[84305],[False],[0.553],[0.812],...,[-5.542],[1],[0.0558],[0.132],[9.92e-06],[0.0794],[0.871],[118.368],[4],[kids]
3,"""C"" is for Cookie",Little Apple Band,[66996],[73lXf5if6MWVWnsgXhK8bd],[Sesame Street and Friends],[8],[86675],[False],[0.664],[0.611],...,[-8.687],[1],[0.0886],[0.12],[0.0],[0.0408],[0.758],[118.443],[4],[kids]
4,"""Christe, Redemptor omnium""",Traditional;Sistine Chapel Choir;Massimo Palom...,[101161],[0jmz4aHEIBCRgrcV2xEkwB],[Classical Christmas],[0],[289133],[False],[0.111],[0.0568],...,[-28.053],[1],[0.0551],[0.99],[0.697],[0.11],[0.0395],[169.401],[1],[sleep]

Se aplica minúscula al nombre de la canción y artista para eliminar repetidos como en el caso anterior.

In [7]:
lower_df = df.copy()
lower_df['track_name'] = lower_df['track_name'].str.lower()
lower_df['artists'] = lower_df['artists'].str.lower()
group2 = lower_df.groupby(["track_name", "artists"], as_index=False).agg(list)

In [8]:
group2.shape

(81206, 21)

In [9]:
group2.head(5)

,track_name,artists,Unnamed: 0,track_id,album_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,!i'll be back!,rilès,[36750],[0fROT4kK5oTm8xO8PX6EJF],[!I'll Be Back!],[52],[178533],[True],[0.823],[0.612],...,[-7.767],[1],[0.248],[0.168],[0.0],[0.109],[0.688],[142.959],[4],[french]
1,"""a"" you're adorable",brian hyland,[92751],[1hH0t381PIXmUVWyG1Vj3p],[The Bashful Blond],[39],[151680],[False],[0.615],[0.375],...,[-10.362],[0],[0.0319],[0.482],[0.0],[0.111],[0.922],[110.72],[4],[rockabilly]
2,"""c"" is for cookie",little apple band,"[66970, 66996]","[1B45DvGMoFWdbAEUH2qliG, 73lXf5if6MWVWnsgXhK8bd]","[The Favorite Songs Of Sesame Street, Sesame S...","[32, 8]","[84305, 86675]","[False, False]","[0.553, 0.664]","[0.812, 0.611]",...,"[-5.542, -8.687]","[1, 1]","[0.0558, 0.0886]","[0.132, 0.12]","[9.92e-06, 0.0]","[0.0794, 0.0408]","[0.871, 0.758]","[118.368, 118.443]","[4, 4]","[kids, kids]"
3,"""christe, redemptor omnium""",traditional;sistine chapel choir;massimo palom...,[101161],[0jmz4aHEIBCRgrcV2xEkwB],[Classical Christmas],[0],[289133],[False],[0.111],[0.0568],...,[-28.053],[1],[0.0551],[0.99],[0.697],[0.11],[0.0395],[169.401],[1],[sleep]
4,"""contemplate this on the tree of woe.""",dillinger four,[82584],[5Zx0Rrkn5RFBMD2PRxX3mI],[C I V I L W A R],[24],[180706],[False],[0.565],[0.977],...,[-3.592],[1],[0.0546],[0.0282],[0.00132],[0.433],[0.387],[106.478],[4],[power-pop]

In [10]:
df_clean = lower_df.copy()
df_clean = df_clean.drop(columns=["Unnamed: 0"])

In [11]:
df_clean.groupby(["track_name", "artists"], as_index=False).agg(list)

,track_name,artists,track_id,album_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,!i'll be back!,rilès,[0fROT4kK5oTm8xO8PX6EJF],[!I'll Be Back!],[52],[178533],[True],[0.823],[0.612],[1],[-7.767],[1],[0.248],[0.168],[0.0],[0.109],[0.688],[142.959],[4],[french]
1,"""a"" you're adorable",brian hyland,[1hH0t381PIXmUVWyG1Vj3p],[The Bashful Blond],[39],[151680],[False],[0.615],[0.375],[0],[-10.362],[0],[0.0319],[0.482],[0.0],[0.111],[0.922],[110.72],[4],[rockabilly]
2,"""c"" is for cookie",little apple band,"[1B45DvGMoFWdbAEUH2qliG, 73lXf5if6MWVWnsgXhK8bd]","[The Favorite Songs Of Sesame Street, Sesame S...","[32, 8]","[84305, 86675]","[False, False]","[0.553, 0.664]","[0.812, 0.611]","[3, 3]","[-5.542, -8.687]","[1, 1]","[0.0558, 0.0886]","[0.132, 0.12]","[9.92e-06, 0.0]","[0.0794, 0.0408]","[0.871, 0.758]","[118.368, 118.443]","[4, 4]","[kids, kids]"
3,"""christe, redemptor omnium""",traditional;sistine chapel choir;massimo palom...,[0jmz4aHEIBCRgrcV2xEkwB],[Classical Christmas],[0],[289133],[False],[0.111],[0.0568],[10],[-28.053],[1],[0.0551],[0.99],[0.697],[0.11],[0.0395],[169.401],[1],[sleep]
4,"""contemplate this on the tree of woe.""",dillinger four,[5Zx0Rrkn5RFBMD2PRxX3mI],[C I V I L W A R],[24],[180706],[False],[0.565],[0.977],[11],[-3.592],[1],[0.0546],[0.0282],[0.00132],[0.433],[0.387],[106.478],[4],[power-pop]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81201,내 맘을 볼 수 있나요,heize,[2oVHb8wyg6oC2iNpGBNvx1],[Hotel del Luna (Original Television Soundtrac...,[63],[225785],[False],[0.397],[0.166],[9],[-10.678],[1],[0.0349],[0.884],[0.0],[0.1],[0.131],[134.708],[4],[k-pop]
81202,시작,gaho,[4kIpBfvK44bxqX7zo8K1oP],[ITAEWON CLASS (Original Television Soundtrack...,[65],[202440],[False],[0.591],[0.818],[4],[-3.532],[1],[0.073],[0.172],[0.0],[0.126],[0.574],[108.107],[4],[k-pop]
81203,약속 (piano solo),yiruma,[4mHc7LUlO3k6AXeFV2EiJK],[Yiruma Official Album 'Piano Therapy' (The Or...,[37],[144533],[False],[0.504],[0.143],[1],[-18.713],[1],[0.0701],[0.98],[0.922],[0.124],[0.0584],[148.786],[4],[new-age]
81204,원펀맨 theme - sad theme,goda,[0tQesiSZJQOdHeAC7r59us],[One Punch Man (Original Soundtrack)],[37],[228000],[False],[0.542],[0.337],[2],[-16.088],[1],[0.0539],[0.985],[0.933],[0.147],[0.443],[159.951],[4],[piano]
81205,행복하길 바래,lim hyung joo,[5epH8xMDeJ4edJjIkKzEdM],[Sassy Girl Choon Hyang (Original Soundtrack)],[39],[185666],[False],[0.361],[0.517],[10],[-6.955],[0],[0.031],[0.711],[7.53e-05],[0.115],[0.308],[94.713],[4],[opera]

In [12]:
df_clean.dtypes

track_id                str
artists                 str
album_name              str
track_name              str
popularity            int64
duration_ms           int64
explicit               bool
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
time_signature        int64
track_genre             str
dtype: object

In [13]:
df_clean = (
    df_clean.groupby(["track_name", "artists"], as_index=False).agg({
        'album_name': 'first',
        'popularity': 'max',
        'duration_ms': 'median',
        'explicit': lambda x: x.mode().iloc[0],
        'danceability': 'mean',
        'energy': 'mean',
        'key': lambda x: x.mode().iloc[0],
        'loudness': 'median',
        'mode': lambda x: x.mode().iloc[0],
        'speechiness': 'mean',
        'acousticness': 'mean',
        'instrumentalness': 'mean',
        'liveness': 'median',
        'valence': 'mean',
        'tempo': 'median',
        'time_signature': lambda x: x.mode().iloc[0],
        'track_genre': lambda x: x.mode().iloc[0],
    })
)

In [14]:
df_clean

,track_name,artists,album_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,!i'll be back!,rilès,!I'll Be Back!,52,178533.0,True,0.8230,0.6120,1,-7.7670,1,0.2480,0.1680,0.000000,0.1090,0.6880,142.9590,4,french
1,"""a"" you're adorable",brian hyland,The Bashful Blond,39,151680.0,False,0.6150,0.3750,0,-10.3620,0,0.0319,0.4820,0.000000,0.1110,0.9220,110.7200,4,rockabilly
2,"""c"" is for cookie",little apple band,The Favorite Songs Of Sesame Street,32,85490.0,False,0.6085,0.7115,3,-7.1145,1,0.0722,0.1260,0.000005,0.0601,0.8145,118.4055,4,kids
3,"""christe, redemptor omnium""",traditional;sistine chapel choir;massimo palom...,Classical Christmas,0,289133.0,False,0.1110,0.0568,10,-28.0530,1,0.0551,0.9900,0.697000,0.1100,0.0395,169.4010,1,sleep
4,"""contemplate this on the tree of woe.""",dillinger four,C I V I L W A R,24,180706.0,False,0.5650,0.9770,11,-3.5920,1,0.0546,0.0282,0.001320,0.4330,0.3870,106.4780,4,power-pop
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81201,내 맘을 볼 수 있나요,heize,Hotel del Luna (Original Television Soundtrack...,63,225785.0,False,0.3970,0.1660,9,-10.6780,1,0.0349,0.8840,0.000000,0.1000,0.1310,134.7080,4,k-pop
81202,시작,gaho,ITAEWON CLASS (Original Television Soundtrack)...,65,202440.0,False,0.5910,0.8180,4,-3.5320,1,0.0730,0.1720,0.000000,0.1260,0.5740,108.1070,4,k-pop
81203,약속 (piano solo),yiruma,Yiruma Official Album 'Piano Therapy' (The Ori...,37,144533.0,False,0.5040,0.1430,1,-18.7130,1,0.0701,0.9800,0.922000,0.1240,0.0584,148.7860,4,new-age
81204,원펀맨 theme - sad theme,goda,One Punch Man (Original Soundtrack),37,228000.0,False,0.5420,0.3370,2,-16.0880,1,0.0539,0.9850,0.933000,0.1470,0.4430,159.9510,4,piano
81205,행복하길 바래,lim hyung joo,Sassy Girl Choon Hyang (Original Soundtrack),39,185666.0,False,0.3610,0.5170,10,-6.9550,0,0.0310,0.7110,0.000075,0.1150,0.3080,94.7130,4,opera

In [15]:
df_clean.shape

(81206, 19)

In [16]:
print(type(df))
print(type(df_clean))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>